// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoxyZjpwq6-LAL9JlP7UsycbpXFj62KgU',
    appId: '1:82330382748:web:dd517ccb503b6dbdb09859',
    messagingSenderId: '82330382748',
    projectId: 'bible-read-39389',
    authDomain: 'bible-read-39389.firebaseapp.com',
    storageBucket: 'bible-read-39389.firebasestorage.app',
    measurementId: 'G-L5X0H71WYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_yNXVmgLKIqpe0TZjbgrGsI-7kYV5MjA',
    appId: '1:82330382748:android:128708aa4357a7f7b09859',
    messagingSenderId: '82330382748',
    projectId: 'bible-read-39389',
    storageBucket: 'bible-read-39389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9H29Y0JdIx60fDxo96Gtp_KDUuOs8Sx0',
    appId: '1:82330382748:ios:33ef61927485ef91b09859',
    messagingSenderId: '82330382748',
    projectId: 'bible-read-39389',
    storageBucket: 'bible-read-39389.firebasestorage.app',
    androidClientId: '82330382748-2p05l088d3gb3c2verqp961i8s4pic3o.apps.googleusercontent.com',
    iosClientId: '82330382748-kv8cr6ehdtjglo5v2iqa6e8ge038kh0s.apps.googleusercontent.com',
    iosBundleId: 'com.bibleread.challenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9H29Y0JdIx60fDxo96Gtp_KDUuOs8Sx0',
    appId: '1:82330382748:ios:0022eaa7adf2d642b09859',
    messagingSenderId: '82330382748',
    projectId: 'bible-read-39389',
    storageBucket: 'bible-read-39389.firebasestorage.app',
    androidClientId: '82330382748-2p05l088d3gb3c2verqp961i8s4pic3o.apps.googleusercontent.com',
    iosClientId: '82330382748-p6nddo8u50pf2295h70lqdrtlvhjsfih.apps.googleusercontent.com',
    iosBundleId: 'com.bibleread.bibleRead',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoxyZjpwq6-LAL9JlP7UsycbpXFj62KgU',
    appId: '1:82330382748:web:0bb77bed2f47c317b09859',
    messagingSenderId: '82330382748',
    projectId: 'bible-read-39389',
    authDomain: 'bible-read-39389.firebaseapp.com',
    storageBucket: 'bible-read-39389.firebasestorage.app',
    measurementId: 'G-SSR7836PWC',
  );

}